site_name: Arief's Space
site_url: https://ariefbudhima.github.io/
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'assets/logo2.gif'
  favicon: 'assets/favicon.ico'
  language: en
  features:
    - header.autohide
extra:
  generator: false
nav:
  - Home: index.html